name: Daily meiri

on:
  schedule:
    # 每天 UTC 时间 05:14 运行 (对应北京时间 13:14)
    - cron: '14 5 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  run-checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          # 如果有 requirements.txt，可以取消下面这行的注释
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run check-in script
        run: python main.py
        env:
          COCO_AUTH_TOKEN: ${{ secrets.COCO_AUTH_TOKEN }}
          ZHSL_AUTH_TOKEN: ${{ secrets.ZHSL_AUTH_TOKEN }}
