name: Daily Checkin Task

on:
  schedule:
    # 设置定时任务，每天 UTC 时间 05:30 (即北京时间 13:30) 运行
    - cron: '55 5 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  run-checkin:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run check-in script
        run: python main.py
        env:
          COCO_AUTH_TOKEN: ${{ secrets.COCO_AUTH_TOKEN }}
          ZHSL_AUTH_TOKEN: ${{ secrets.ZHSL_AUTH_TOKEN }}
