name: Daily Checkin Task

on:
  schedule:
    # 设置定时任务，每天 UTC 时间 16:00 (即北京时间第二天 00:00) 运行
    # 注意：cron 语法是 "分 时 日 月 周"
    - cron: '0 16 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  run-checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          # 如果有 requirements.txt，可以取消下面这行的注释
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run check-in script
        run: python main.py
        env:
          COCO_AUTH_TOKEN: ${{ secrets.COCO_AUTH_TOKEN }}
          ZHSL_AUTH_TOKEN: ${{ secrets.ZHSL_AUTH_TOKEN }}
